### ISSUE TITLE
You want a username like mine. Skid 😂 

### ISSUE THREAD

**Issue by e6** [imvast/Github-Username-Checker#1]

**Comment by imvast** [comment]
kid must want attention making a random issue for no reason

**Comment by imvast** [comment]
🤡

**Comment by imvast** [comment]
irrelevant attention seeker the owner of skid.wiki is the biggest skid of them all but you wouldnt know because you are just a random fanboy

**Comment by imvast** [comment]
wow such a big word for a little boy like you. did you skid that from google too? also you arent fooling anybody ik this is your alt dumb fuck

**Comment by imvast** [comment]
only you would dick ride me this hard
